### ISSUE TITLE
Tracking Issue for DataPointIterator

### ISSUE THREAD

**Issue by gfoidl** [gfoidl/DataCompression#16]
This issue is meant to keep track of the changes done on behalf of `DataPointIterator`.

* [x] DeadBandCompression -- https://github.com/gfoidl/DataCompression/pull/15
* [x] SwingingDoorCompression -- https://github.com/gfoidl/DataCompression/pull/17
* [ ] ~Return type of interface `ICompression` -- https://github.com/gfoidl/DataCompression/pull/18~

**Comment by gfoidl** [comment]
#18 will go for [2.0.0](https://github.com/gfoidl/DataCompression/milestone/1), so this isssue can be closed, as #15 and #17 are done.
